apiVersion: v1
kind: Service
metadata:
  name: postgres-service # nome usado para ligar à base de dados
  labels:
    app.kubernetes.io/name: postgres-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres