apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app.kubernetes.io/name: postgres-statefulset
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-pv-volume
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      containers:
        - name: postgres
          image: docker.io/bitnami/postgresql:17.4.0
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_USER
          volumeMounts:
            - name: postgres-pv-volume
              mountPath: "/var/lib/postgresql/data"
      initContainers:
        - name: install
          image: busybox:latest # imagem leve para executar comandos simples, como chmod
          command:
          - chmod
          - -R
          - "777"
          - /var/lib/postgresql/data
          volumeMounts:
          - name: postgres-pv-volume
            mountPath: "/var/lib/postgresql/data"